services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: thana
      POSTGRES_PASSWORD: 8870
      POSTGRES_DB: PlacementDB
    ports:
      - "5433:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgresdata: